In [1]:
import pandas as pd
import datetime as dt
from dataretrieval import nwis
from dataretrieval import waterdata
from Python_Files import data
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
upstream_id = "10155200"
downstream_id = "10155500"
start_date = '2016-01-01'
end_date = '2025-12-31'

discharge = data.get_discharge(upstream_id,downstream_id,start_date,end_date)
#width = data.get_width()

In [3]:
# possible_validation = pd.merge(discharge,cleaning,how='inner',on='Date').dropna()
# sample_daily["Downstream Width (ft)"] = sample_daily["Downstream Width (ft)"].ffill().bfill()
# possible_validation.head(30)

In [4]:
datum, up_MSE, down_MSE = data.log_transform(discharge,'depth')
print(f"Upstream Training MSE: {up_MSE:.4f}")
print(f"DownstreamTraining MSE: {down_MSE:.4f}")

datum.tail(10)

Upstream Training MSE: 0.0018
DownstreamTraining MSE: 0.0007

,Upstream Mean Discharge (cfs),Upstream Datum (ft),Downstream Mean Discharge (cfs),Downstream Datum (ft)
Date,,,,
2025-12-18,135.0,0.808600,166.0,3.527459
2025-12-23,136.0,0.811514,163.0,3.509544
2025-12-24,136.0,0.811514,163.0,3.509544
2025-12-25,136.0,0.811514,168.0,3.539274
2025-12-26,136.0,0.811514,169.0,3.545143
2025-12-27,139.0,0.820188,181.0,3.613696
2025-12-28,137.0,0.814416,173.0,3.568373
2025-12-29,134.0,0.805676,159.0,3.485282
2025-12-30,140.0,0.823059,163.0,3.509544
2025-12-31,141.0,0.825918,163.0,3.509544

In [5]:
years = datum.index.year.unique()
print(years)

Index([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], dtype='int32', name='Date')

In [ ]:
from concurrent.futures import ThreadPoolExecutor
def continuous(site,years):
    for i in years:
        
        d, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{site}",
                                            parameter_code='00065',
                                            time=f"{years[i]}-01-01/{years[i+1]}-12-31",
                                            properties=["time","value","unit_of_measure"])

In [6]:
#continuous gage depth below surface? every2years
#Can't be in data.py due to weak processing power, bear with the multiple cells 

#2016-2017
up_2016_2017, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{upstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[0]}-01-01/{years[1]}-12-31",
                                        properties=["time","value","unit_of_measure"])
up_2016_2017.set_index("time",inplace=True)
up_2016_2017.index = up_2016_2017.index.date
up_2016_2017.index = pd.to_datetime(up_2016_2017.index)
up_2016_2017 = up_2016_2017.resample('D').first()

down_2016_2017, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{downstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[0]}-01-01/{years[1]}-12-31",
                                        properties=["time","value","unit_of_measure"])
down_2016_2017.set_index("time",inplace=True)
down_2016_2017.index = down_2016_2017.index.date
down_2016_2017.index = pd.to_datetime(down_2016_2017.index)
down_2016_2017 = down_2016_2017.resample('D').first()

In [7]:
#2018-2019
up_2018_2019, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{upstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[2]}-01-01/{years[3]}-12-31",
                                        properties=["time","value","unit_of_measure"])
up_2018_2019.set_index("time",inplace=True)
up_2018_2019.index = up_2018_2019.index.date
up_2018_2019.index = pd.to_datetime(up_2018_2019.index)
up_2018_2019 = up_2018_2019.resample('D').first()

down_2018_2019, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{downstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[2]}-01-01/{years[3]}-12-31",
                                        properties=["time","value","unit_of_measure"])
down_2018_2019.set_index("time",inplace=True)
down_2018_2019.index = down_2018_2019.index.date
down_2018_2019.index = pd.to_datetime(down_2018_2019.index)
down_2018_2019 = down_2018_2019.resample('D').first()

In [8]:
#2020-2021
up_2020_2021, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{upstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[4]}-01-01/{years[5]}-12-31",
                                        properties=["time","value","unit_of_measure"])
up_2020_2021.set_index("time",inplace=True)
up_2020_2021.index = up_2020_2021.index.date
up_2020_2021.index = pd.to_datetime(up_2020_2021.index)
up_2020_2021 = up_2020_2021.resample('D').first()

down_2020_2021, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{downstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[4]}-01-01/{years[5]}-12-31",
                                        properties=["time","value","unit_of_measure"])
down_2020_2021.set_index("time",inplace=True)
down_2020_2021.index = down_2020_2021.index.date
down_2020_2021.index = pd.to_datetime(down_2020_2021.index)
down_2020_2021 = down_2020_2021.resample('D').first()

In [9]:
#2022-2023
up_2022_2023, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{upstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[6]}-01-01/{years[7]}-12-31",
                                        properties=["time","value","unit_of_measure"])
up_2022_2023.set_index("time",inplace=True)
up_2022_2023.index = up_2022_2023.index.date
up_2022_2023.index = pd.to_datetime(up_2022_2023.index)
up_2022_2023 = up_2022_2023.resample('D').first()

down_2022_2023, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{downstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[6]}-01-01/{years[7]}-12-31",
                                        properties=["time","value","unit_of_measure"])
down_2022_2023.set_index("time",inplace=True)
down_2022_2023.index = down_2022_2023.index.date
down_2022_2023.index = pd.to_datetime(down_2022_2023.index)
down_2022_2023 = down_2022_2023.resample('D').first()

In [10]:
#2024-2025
up_2024_2025, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{upstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[8]}-01-01/{years[9]}-12-31",
                                        properties=["time","value","unit_of_measure"])
up_2024_2025.set_index("time",inplace=True)
up_2024_2025.index = up_2024_2025.index.date
up_2024_2025.index = pd.to_datetime(up_2024_2025.index)
up_2024_2025 = up_2024_2025.resample('D').first()

down_2024_2025, m = waterdata.get_continuous(monitoring_location_id= f"USGS-{downstream_id}",
                                        parameter_code='00065',
                                        time=f"{years[8]}-01-01/{years[9]}-12-31",
                                        properties=["time","value","unit_of_measure"])
down_2024_2025.set_index("time",inplace=True)
down_2024_2025.index = down_2024_2025.index.date
down_2024_2025.index = pd.to_datetime(down_2024_2025.index)
down_2024_2025 = down_2024_2025.resample('D').first()

In [11]:
#combining daily average to surface
surface_upstream = pd.concat([up_2016_2017,up_2018_2019,up_2020_2021,up_2022_2023,up_2024_2025])
surface_upstream.index.name = "Date"
surface_upstream = surface_upstream.drop(columns = ["unit_of_measure"])
surface_upstream = surface_upstream.rename(columns={"value":"Upstream to Surface (ft)"})

surface_downstream = pd.concat([down_2016_2017,down_2018_2019,down_2020_2021,down_2022_2023,down_2024_2025])
surface_downstream.index.name = "Date"
surface_downstream = surface_downstream.drop(columns = ["unit_of_measure"])
surface_downstream = surface_downstream.rename(columns={"value":"Downstream to Surface (ft)"})

to_surface = pd.merge(surface_upstream,surface_downstream,how='outer',on = "Date")

In [12]:
#merge and add the to surfae and to gauge values

discharge_depth = pd.merge(to_surface,datum,how='outer',on="Date")
discharge_depth["Upstream Depth (ft)"] = discharge_depth["Upstream Datum (ft)"] + discharge_depth["Upstream to Surface (ft)"]
discharge_depth["Downstream Depth (ft)"] = discharge_depth["Downstream Datum (ft)"] + discharge_depth["Downstream to Surface (ft)"]
discharge_depth = discharge_depth.drop(columns=["Upstream to Surface (ft)","Downstream to Surface (ft)","Upstream Datum (ft)","Downstream Datum (ft)"])

In [13]:
w, up_MSE, down_MSE = data.log_transform(discharge,"width")
print(f"Upstream Training MSE: {up_MSE:.4f}")
print(f"DownstreamTraining MSE: {down_MSE:.4f}")

Upstream Training MSE: 0.0055
DownstreamTraining MSE: 0.0041

In [14]:
w = w.drop(columns=["Upstream Mean Discharge (cfs)","Downstream Mean Discharge (cfs)"],axis=1)
data_set = pd.merge(discharge_depth,w,how='outer',on="Date")
data_set.head(50)

,Upstream Mean Discharge (cfs),Downstream Mean Discharge (cfs),Upstream Depth (ft),Downstream Depth (ft),Upstream Width (ft),Downstream Width (ft)
Date,,,,,,
2016-01-01,137.0,146.0,1.624416,7.003261,58.532544,56.496681
2016-01-02,134.0,147.0,1.605676,7.059753,58.455077,56.519038
2016-01-03,136.0,146.0,1.611514,7.043261,58.506900,56.496681
2016-01-04,135.0,144.0,1.608600,7.000180,58.481079,56.451532
2016-01-05,134.0,145.0,1.605676,6.966737,58.455077,56.474180
2016-01-06,136.0,147.0,1.611514,6.989753,58.506900,56.519038
2016-01-07,136.0,150.0,1.611514,7.019040,58.506900,56.585258
2016-01-08,137.0,149.0,1.614416,7.022642,58.532544,56.563324
2016-01-09,136.0,149.0,1.621514,7.022642,58.506900,56.563324
2016-01-10,135.0,146.0,1.608600,6.993261,58.481079,56.496681
2016-01-11,137.0,146.0,1.614416,6.993261,58.532544,56.496681
2016-01-12,135.0,144.0,1.625000,6.980180,65.000000,56.451532
2016-01-13,134.0,144.0,1.605676,6.980180,58.455077,56.451532
2016-01-14,134.0,146.0,1.605676,7.170000,58.455077,57.000000
2016-01-15,136.0,147.0,1.611514,6.999753,58.506900,56.519038
2016-01-16,136.0,147.0,1.611514,6.999753,58.506900,56.519038
2016-01-17,137.0,148.0,1.624416,7.006213,58.532544,56.541251
2016-01-18,138.0,149.0,1.627308,7.022642,58.558013,56.563324
2016-01-19,136.0,149.0,1.621514,7.032642,58.506900,56.563324
2016-01-20,136.0,151.0,1.611514,7.025408,58.506900,56.607054
2016-01-21,136.0,147.0,1.611514,7.019753,58.506900,56.519038
2016-01-22,136.0,147.0,1.611514,7.009753,58.506900,56.519038
2016-01-23,135.0,148.0,1.608600,7.016213,58.481079,56.541251
2016-01-24,131.0,149.0,1.596835,7.032642,58.375961,56.563324
2016-01-25,131.0,149.0,1.596835,7.022642,58.375961,56.563324
2016-01-26,130.0,147.0,1.593865,7.009753,58.349210,56.519038
2016-01-27,131.0,146.0,1.596835,7.003261,58.375961,56.496681
2016-01-28,130.0,146.0,1.593865,7.003261,58.349210,56.496681
2016-01-29,131.0,147.0,1.596835,6.999753,58.375961,56.519038
2016-01-30,135.0,163.0,1.608600,7.099544,58.481079,56.858508
2016-01-31,131.0,153.0,1.606835,7.118052,58.375961,56.650242
2016-02-01,133.0,150.0,1.602740,7.069040,58.428891,56.585258
2016-02-02,131.0,149.0,1.596835,7.032642,58.375961,56.563324
2016-02-03,133.0,152.0,1.602740,7.071745,58.428891,56.628715
2016-02-04,134.0,151.0,1.615676,7.075408,58.455077,56.607054
2016-02-05,134.0,153.0,1.615676,7.068052,58.455077,56.650242
2016-02-06,134.0,149.0,1.615676,7.042642,58.455077,56.563324
2016-02-07,134.0,150.0,1.615676,7.039040,58.455077,56.585258
2016-02-08,134.0,149.0,1.615676,7.032642,58.455077,56.563324
2016-02-09,134.0,149.0,1.615676,7.032642,58.455077,56.563324
2016-02-10,134.0,148.0,1.615676,7.026213,58.455077,56.541251
2016-02-11,135.0,147.0,1.618600,7.009753,58.481079,56.519038
2016-02-12,137.0,148.0,1.624416,7.016213,58.532544,56.541251
2016-02-13,141.0,151.0,1.645918,7.035408,58.633390,56.607054
2016-02-14,138.0,150.0,1.637308,7.059040,58.558013,56.585258
2016-02-15,136.0,157.0,1.631514,7.082986,58.506900,56.735045
2016-02-16,133.0,157.0,1.622740,7.142986,58.428891,56.735045
2016-02-17,131.0,158.0,1.606835,7.109148,58.375961,56.755927
2016-02-18,133.0,189.0,1.612740,7.307597,58.428891,57.348336
2016-02-19,136.0,193.0,1.641514,7.619047,58.506900,57.417992

In [15]:
cleaned_data = data_set.dropna()
range = pd.date_range(start=cleaned_data.index.min(), end=cleaned_data.index.max(), freq='D')

missing_dates = range.difference(cleaned_data.index)
print("Missing dates:", missing_dates)

Missing dates: DatetimeIndex(['2017-05-11', '2017-05-12', '2017-05-13', '2017-05-14',
               '2017-05-15', '2017-05-16', '2017-05-17', '2017-08-15',
               '2017-08-16', '2017-08-17', '2017-08-18', '2017-08-19',
               '2017-08-20', '2019-06-10', '2019-06-11', '2019-06-12',
               '2019-06-13', '2019-06-14', '2019-06-15', '2019-06-16',
               '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20',
               '2019-06-21', '2019-06-22', '2019-06-23', '2019-08-15',
               '2019-08-16', '2019-08-17', '2019-08-18', '2019-08-19',
               '2019-08-20', '2019-08-21', '2023-01-21', '2023-01-22',
               '2023-01-23', '2023-01-24', '2023-05-04', '2023-07-26',
               '2023-07-27', '2023-07-28', '2023-07-29', '2023-07-30',
               '2024-08-03', '2024-08-04', '2024-08-05', '2024-08-06',
               '2024-08-08', '2024-08-09', '2024-08-10', '2024-08-11',
               '2024-08-12', '2024-08-13', '2024-08-14', '2024-08-15',
               '2024-08-17', '2024-08-18', '2025-12-19', '2025-12-20',
               '2025-12-21', '2025-12-22'],
              dtype='datetime64[ns]', freq=None)